name: "Continuous Deployment"
on:
  push:
    branches: 
      - dev 

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
           ghcr.io/ingsis-grupo1-2024/printscript-ui-dev:${{ steps.short-sha.outputs.sha }}
           ghcr.io/ingsis-grupo1-2024/printscript-ui-dev:latest
           
          build-args: |
            ACTOR=${{ github.repository_owner }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
            VITE_FRONTEND_URL= ${{ secrets.FRONTEND_URL }}
            VITE_BACKEND_URL=${{ secrets.BACKEND_URL }}
            VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
            VITE_AUTH0_SCOPE=${{ secrets.AUTH0_SCOPE }}
            VITE_MANAGER_URL=${{ secrets.MANAGER_URL }}
            VITE_CONFIGURATIONS_URL=${{ secrets.CONFIGURATIONS_URL }}

  deploy_to_vm:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/deploy.yml@main
    needs: push_to_registry
    secrets: inherit 
    with:
      container-name: printscript-ui
