name: "Continuous Deployment to main"
on:
  push:
    branches:
      - master
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: deployment
    steps: 
    - uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/cd.yml@main
      with:
        image-name: printscript-ui
        env-name: main
        additional-build-args: FRONTEND_URL=${{ secrets.FRONTEND_URL }}
