name: "Continuous Deployment to main"
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/cd.yml@main
    with:
      image-name: printscript-ui
      env-name: main
      additional-build-args: ${{FRONTEND_URL=secrets.FRONTEND_URL BACKEND_URL=secrets.BACKEND_URL AUTH0_DOMAIN=secrets.AUTH0_DOMAIN AUTH0_CLIENT_ID=secrets.AUTH0_CLIENT_ID AUTH0_AUDIENCE= secrets.AUTH0_AUDIENCE AUTH0_SCOPE=secrets.AUTH0_SCOPE MANAGER_URL=secrets.MANAGER_URL CONFIGURATIONS_URL=secrets.CONFIGURATIONS_URL}}
